import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { DataSource, EntityManager } from 'typeorm';
import { CreateExchangeDto } from './dto/create-exchange.dto';
import { ReturnsService } from '../returns/returns.service';
import { SalesService } from '../sales/sales.service';
import { ItemSerialsService } from '../item-serials/item-serials.service';
import { Item } from '../items/entities/item.entity';
import { Sale } from '../sales/entities/sale.entity';
import { SaleReturn } from '../returns/entities/sale-return.entity';
import { PurchaseReturn } from '../returns/entities/purchase-return.entity';
import { CreateSaleDto } from '../sales/dto/create-sale.dto';

export interface ExchangeResult {
  saleReturn: SaleReturn;
  purchaseReturn?: PurchaseReturn;
  sale: Sale;
  /** Store credit generated by the give-back leg. */
  returnCredit: number;
  /** Supplier warranty credit booked (0 when none). */
  supplierCredit: number;
  /** Cash collected from the customer now. */
  cashCollected: number;
  /** Net total of the new goods (after discount). */
  newSaleNet: number;
  /**
   * newSaleNet − returnCredit − cashCollected.
   *   > 0 → customer still owes this much (stays as A/R).
   *   < 0 → customer has this much leftover credit / owed a refund.
   *   ≈ 0 → clean swap, balances net to zero.
   */
  difference: number;
}

/**
 * Atomic "exchange" — return old goods and buy new in ONE transaction, with
 * the customer's give-back value carried straight onto the new purchase.
 *
 * Legs (all-or-nothing):
 *   A. Sale return (RESTOCK or CLAIMED_TO_COMPANY) → credits the customer the
 *      full return value as store credit (no cash refund on the return itself).
 *   B. Optional supplier warranty credit (WARRANTY_CREDIT purchase return, no
 *      stock) → credits our supplier ledger by the typed amount.
 *   C. New sale → the customer pays the cash difference now; the residual is
 *      offset by the store credit from leg A (the customer ledger nets them).
 *      Serials on the new goods are bound DELIVERED — the customer walks out
 *      with them regardless of the residual, which is credit-backed, not debt.
 *
 * NOTE: like plain returns, an exchange does not currently enqueue an outbox
 * event, so it isn't pushed to the cloud. Acceptable while returns are
 * cloud-invisible; revisit with a dedicated EXCHANGE_CREATED event if
 * multi-node reporting ever needs it.
 */
@Injectable()
export class ExchangeService {
  constructor(
    private readonly dataSource: DataSource,
    private readonly returns: ReturnsService,
    private readonly sales: SalesService,
    private readonly itemSerials: ItemSerialsService,
  ) {}

  async create(dto: CreateExchangeDto): Promise<ExchangeResult> {
    const cashCollected = Number((dto.paymentAmount ?? 0).toFixed(2));
    if (cashCollected > 0 && !dto.paymentAccountId) {
      throw new BadRequestException(
        'A cash difference needs a destination account (paymentAccountId).',
      );
    }
    if (dto.supplierCredit && (dto.returnDisposition ?? 'RESTOCK') !== 'CLAIMED_TO_COMPANY') {
      throw new BadRequestException(
        'A supplier warranty credit only applies when the returned goods were claimed to the company (returnDisposition = CLAIMED_TO_COMPANY).',
      );
    }

    return this.dataSource.transaction(async (manager) => {
      // ── Leg A: give-back (store credit, never a cash refund here) ──────────
      const saleReturn = await this.returns.createSaleReturnInTransaction(manager, {
        saleId: dto.originalSaleId,
        customerId: dto.customerId,
        storeId: dto.storeId,
        disposition: dto.returnDisposition ?? 'RESTOCK',
        reason: dto.returnReason ?? 'Exchange give-back',
        lines: dto.returnLines,
      });
      const returnCredit = Number(saleReturn.totalAmount);

      // ── Leg B: optional supplier warranty credit (financial only) ─────────
      let purchaseReturn: PurchaseReturn | undefined;
      let supplierCredit = 0;
      if (dto.supplierCredit && dto.supplierCredit.amount > 0) {
        supplierCredit = Number(dto.supplierCredit.amount.toFixed(2));
        purchaseReturn = await this.returns.createPurchaseReturnInTransaction(manager, {
          supplierId: dto.supplierCredit.supplierId,
          storeId: dto.storeId,
          disposition: 'WARRANTY_CREDIT',
          reason:
            dto.supplierCredit.reason ??
            `Warranty credit for exchange ${saleReturn.returnNo}`,
          // One representative line carries the credit amount; no stock moves.
          lines: [
            {
              itemId: dto.returnLines[0].itemId,
              quantity: 1,
              unitPrice: supplierCredit,
            },
          ],
        });
      }

      // ── Leg C: the new sale ───────────────────────────────────────────────
      // paidAmount = the cash difference collected now. The residual
      // (newNet − cash) is offset by the store credit from leg A via the
      // customer ledger, so we skip the credit-limit gate.
      const saleDto: CreateSaleDto = {
        customerId: dto.customerId,
        storeId: dto.storeId,
        discount: dto.discount,
        notes: dto.notes ?? `Exchange against ${saleReturn.returnNo}`,
        lines: dto.saleLines.map((l) => ({
          itemId: l.itemId,
          quantity: l.quantity,
          unitPrice: l.unitPrice,
        })),
        paidAmount: cashCollected,
        paymentMethod: cashCollected > 0 ? 'CASH' : 'CREDIT',
        accountId: cashCollected > 0 ? dto.paymentAccountId : undefined,
      };
      const sale = await this.sales.createInTransaction(manager, saleDto, {
        skipCreditGate: true,
      });

      // Bind new-goods serials as DELIVERED — the customer takes them now.
      await this.bindNewSaleSerials(manager, sale, dto);

      // ── Link the give-back to the replacement sale (both-way trace) ───────
      saleReturn.replacementSaleId = sale.id;
      await manager.getRepository(SaleReturn).save(saleReturn);

      const newSaleNet = Number(sale.netAmount);
      const difference = Number(
        (newSaleNet - returnCredit - cashCollected).toFixed(2),
      );

      return {
        saleReturn,
        purchaseReturn,
        sale,
        returnCredit,
        supplierCredit,
        cashCollected,
        newSaleNet,
        difference,
      };
    });
  }

  /**
   * Bind each serialised new-sale line to the invoice as DELIVERED, stamping
   * warranty from the item's cover config — mirrors the full-pay branch of the
   * voucher flow. Validates serial counts for items that require them.
   */
  private async bindNewSaleSerials(
    manager: EntityManager,
    sale: Sale,
    dto: CreateExchangeDto,
  ): Promise<void> {
    const itemRepo = manager.getRepository(Item);
    for (const ln of dto.saleLines) {
      const it = await itemRepo.findOne({ where: { id: ln.itemId } });
      if (!it) throw new NotFoundException(`Item ${ln.itemId} not found`);
      if (!it.tracksSerials) continue;
      const provided = (ln.serials ?? []).map((s) => s.trim()).filter(Boolean);
      if (it.serialRequiredOnSale && provided.length !== ln.quantity) {
        throw new BadRequestException(
          `${it.name}: ${ln.quantity} serial number${ln.quantity === 1 ? '' : 's'} required (got ${provided.length}). One serial per unit.`,
        );
      }
      if (
        !it.serialRequiredOnSale &&
        provided.length > 0 &&
        provided.length !== ln.quantity
      ) {
        throw new BadRequestException(
          `${it.name}: either supply ${ln.quantity} serial${ln.quantity === 1 ? '' : 's'} (one per unit) or leave the box empty.`,
        );
      }
      if (new Set(provided).size !== provided.length) {
        throw new BadRequestException(
          `${it.name}: duplicate serial numbers within the line.`,
        );
      }
      for (const serial of provided) {
        await this.itemSerials.bindToSale(
          {
            serial,
            itemId: ln.itemId,
            saleInvoiceNo: sale.invoiceNo,
            soldAt: sale.createdAt,
            soldToCustomerId: dto.customerId,
            warrantyDays: it.hasWarranty ? it.warrantyDays ?? undefined : undefined,
            warrantyType: it.hasWarranty ? it.warrantyType ?? undefined : undefined,
          },
          manager,
        );
      }
    }
  }
}
