import { BadRequestException, Injectable, NotFoundException } from '@nestjs/common';
import { DataSource, EntityManager, IsNull, Not } from 'typeorm';
import { CreateExchangeDto } from './dto/create-exchange.dto';
import { ReturnsService } from '../returns/returns.service';
import { SalesService } from '../sales/sales.service';
import { ItemSerialsService } from '../item-serials/item-serials.service';
import { Item } from '../items/entities/item.entity';
import { Sale } from '../sales/entities/sale.entity';
import { SaleReturn } from '../returns/entities/sale-return.entity';
import { PurchaseReturn } from '../returns/entities/purchase-return.entity';
import { CreateSaleDto } from '../sales/dto/create-sale.dto';

/** Read model for the exchange list / detail — the three legs as one row. */
export interface ExchangeSummary {
  saleReturnId: string;
  returnNo: string;
  createdAt: Date;
  customerId?: string;
  invoiceNo?: string;
  saleId?: string;
  returnCredit: number;
  newSaleNet: number;
  cashCollected: number;
  difference: number;
  supplierCreditNo?: string;
  supplierCredit: number;
  reversedAt: Date | null;
  reversalReason: string | null;
}

export interface ExchangeResult {
  saleReturn: SaleReturn;
  purchaseReturn?: PurchaseReturn;
  sale: Sale;
  /** Store credit generated by the give-back leg. */
  returnCredit: number;
  /** Supplier warranty credit booked (0 when none). */
  supplierCredit: number;
  /** Cash collected from the customer now. */
  cashCollected: number;
  /** Net total of the new goods (after discount). */
  newSaleNet: number;
  /**
   * newSaleNet − returnCredit − cashCollected.
   *   > 0 → customer still owes this much (stays as A/R).
   *   < 0 → customer has this much leftover credit / owed a refund.
   *   ≈ 0 → clean swap, balances net to zero.
   */
  difference: number;
}

/**
 * Atomic "exchange" — return old goods and buy new in ONE transaction, with
 * the customer's give-back value carried straight onto the new purchase.
 *
 * Legs (all-or-nothing):
 *   A. Sale return (RESTOCK or CLAIMED_TO_COMPANY) → credits the customer the
 *      full return value as store credit (no cash refund on the return itself).
 *   B. Optional supplier warranty credit (WARRANTY_CREDIT purchase return, no
 *      stock) → credits our supplier ledger by the typed amount.
 *   C. New sale → the customer pays the cash difference now; the residual is
 *      offset by the store credit from leg A (the customer ledger nets them).
 *      Serials on the new goods are bound DELIVERED — the customer walks out
 *      with them regardless of the residual, which is credit-backed, not debt.
 *
 * NOTE: like plain returns, an exchange does not currently enqueue an outbox
 * event, so it isn't pushed to the cloud. Acceptable while returns are
 * cloud-invisible; revisit with a dedicated EXCHANGE_CREATED event if
 * multi-node reporting ever needs it.
 */
@Injectable()
export class ExchangeService {
  constructor(
    private readonly dataSource: DataSource,
    private readonly returns: ReturnsService,
    private readonly sales: SalesService,
    private readonly itemSerials: ItemSerialsService,
  ) {}

  async create(dto: CreateExchangeDto): Promise<ExchangeResult> {
    const cashCollected = Number((dto.paymentAmount ?? 0).toFixed(2));
    if (cashCollected > 0 && !dto.paymentAccountId) {
      throw new BadRequestException(
        'A cash difference needs a destination account (paymentAccountId).',
      );
    }
    if (dto.supplierCredit && (dto.returnDisposition ?? 'RESTOCK') !== 'CLAIMED_TO_COMPANY') {
      throw new BadRequestException(
        'A supplier warranty credit only applies when the returned goods were claimed to the company (returnDisposition = CLAIMED_TO_COMPANY).',
      );
    }

    return this.dataSource.transaction(async (manager) => {
      // ── Leg A: give-back (store credit, never a cash refund here) ──────────
      const saleReturn = await this.returns.createSaleReturnInTransaction(manager, {
        saleId: dto.originalSaleId,
        customerId: dto.customerId,
        storeId: dto.storeId,
        disposition: dto.returnDisposition ?? 'RESTOCK',
        reason: dto.returnReason ?? 'Exchange give-back',
        lines: dto.returnLines,
      });
      const returnCredit = Number(saleReturn.totalAmount);

      // ── Leg B: optional supplier warranty credit (financial only) ─────────
      let purchaseReturn: PurchaseReturn | undefined;
      let supplierCredit = 0;
      if (dto.supplierCredit && dto.supplierCredit.amount > 0) {
        supplierCredit = Number(dto.supplierCredit.amount.toFixed(2));
        purchaseReturn = await this.returns.createPurchaseReturnInTransaction(manager, {
          supplierId: dto.supplierCredit.supplierId,
          storeId: dto.storeId,
          disposition: 'WARRANTY_CREDIT',
          reason:
            dto.supplierCredit.reason ??
            `Warranty credit for exchange ${saleReturn.returnNo}`,
          // One representative line carries the credit amount; no stock moves.
          lines: [
            {
              itemId: dto.returnLines[0].itemId,
              quantity: 1,
              unitPrice: supplierCredit,
            },
          ],
        });
      }

      // ── Leg C: the new sale ───────────────────────────────────────────────
      // paidAmount = the cash difference collected now. The residual
      // (newNet − cash) is offset by the store credit from leg A via the
      // customer ledger, so we skip the credit-limit gate.
      const saleDto: CreateSaleDto = {
        customerId: dto.customerId,
        storeId: dto.storeId,
        discount: dto.discount,
        notes: dto.notes ?? `Exchange against ${saleReturn.returnNo}`,
        lines: dto.saleLines.map((l) => ({
          itemId: l.itemId,
          quantity: l.quantity,
          unitPrice: l.unitPrice,
        })),
        paidAmount: cashCollected,
        paymentMethod: cashCollected > 0 ? 'CASH' : 'CREDIT',
        accountId: cashCollected > 0 ? dto.paymentAccountId : undefined,
      };
      const sale = await this.sales.createInTransaction(manager, saleDto, {
        skipCreditGate: true,
      });

      // Bind new-goods serials as DELIVERED — the customer takes them now.
      await this.bindNewSaleSerials(manager, sale, dto);

      // ── Link the legs together (both-way trace) ───────────────────────────
      saleReturn.replacementSaleId = sale.id;
      await manager.getRepository(SaleReturn).save(saleReturn);
      if (purchaseReturn) {
        // Without this the supplier-credit leg is findable only by reading its
        // reason text, so reversing the exchange would leave it standing.
        purchaseReturn.linkedSaleReturnId = saleReturn.id;
        await manager.getRepository(PurchaseReturn).save(purchaseReturn);
      }

      const newSaleNet = Number(sale.netAmount);
      const difference = Number(
        (newSaleNet - returnCredit - cashCollected).toFixed(2),
      );

      return {
        saleReturn,
        purchaseReturn,
        sale,
        returnCredit,
        supplierCredit,
        cashCollected,
        newSaleNet,
        difference,
      };
    });
  }

  /**
   * Bind each serialised new-sale line to the invoice as DELIVERED, stamping
   * warranty from the item's cover config — mirrors the full-pay branch of the
   * voucher flow. Validates serial counts for items that require them.
   */
  /**
   * Exchanges have no table of their own — one IS a sale return carrying a
   * `replacementSaleId`, plus the sale it points at and any linked supplier
   * credit. So listing them means listing those returns and composing the legs,
   * which is also why an exchange is addressed by its give-back return id.
   */
  async list(): Promise<ExchangeSummary[]> {
    const returns = await this.dataSource.getRepository(SaleReturn).find({
      where: { replacementSaleId: Not(IsNull()) },
      order: { createdAt: 'DESC' },
    });
    return Promise.all(returns.map((r) => this.compose(r)));
  }

  async findOne(saleReturnId: string): Promise<ExchangeSummary> {
    const saleReturn = await this.dataSource
      .getRepository(SaleReturn)
      .findOne({ where: { id: saleReturnId } });
    if (!saleReturn) {
      throw new NotFoundException(`Sale return ${saleReturnId} not found`);
    }
    if (!saleReturn.replacementSaleId) {
      throw new BadRequestException(
        `Return ${saleReturn.returnNo} is a plain return, not an exchange.`,
      );
    }
    return this.compose(saleReturn);
  }

  /**
   * Undo a whole exchange in one transaction — replacement sale, give-back
   * return, and the supplier warranty credit if one was booked.
   *
   * Order is forced: the sale goes first. `ReturnsService` refuses to reverse a
   * give-back while its replacement sale still stands, because removing the
   * store credit that funded the swap would leave the customer owing for goods
   * they exchanged into. Doing it here in the right order means the caller never
   * has to know that rule.
   *
   * Idempotent by construction: each leg's own reversal short-circuits on
   * `reversedAt`, so re-running after a partial failure finishes the job rather
   * than double-unwinding.
   */
  async reverse(
    saleReturnId: string,
    opts: { reason: string; userId?: string },
  ): Promise<ExchangeSummary> {
    if (!opts.reason || opts.reason.trim().length === 0) {
      throw new BadRequestException('Reversal requires a reason.');
    }
    const reason = opts.reason.trim();

    return this.dataSource.transaction(async (manager) => {
      const saleReturn = await manager
        .getRepository(SaleReturn)
        .findOne({ where: { id: saleReturnId } });
      if (!saleReturn) {
        throw new NotFoundException(`Sale return ${saleReturnId} not found`);
      }
      if (!saleReturn.replacementSaleId) {
        throw new BadRequestException(
          `Return ${saleReturn.returnNo} is a plain return, not an exchange — reverse it directly.`,
        );
      }

      await this.sales.reverseInTransaction(
        manager,
        saleReturn.replacementSaleId,
        { reason: `Exchange reversal: ${reason}`, userId: opts.userId },
      );

      await this.returns.reverseSaleReturnInTransaction(manager, saleReturn.id, {
        reason: `Exchange reversal: ${reason}`,
        userId: opts.userId,
      });

      const credit = await manager
        .getRepository(PurchaseReturn)
        .findOne({ where: { linkedSaleReturnId: saleReturn.id } });
      if (credit) {
        await this.returns.reversePurchaseReturnInTransaction(
          manager,
          credit.id,
          { reason: `Exchange reversal: ${reason}`, userId: opts.userId },
        );
      }

      const refreshed = await manager
        .getRepository(SaleReturn)
        .findOneOrFail({ where: { id: saleReturn.id } });
      return this.compose(refreshed, manager);
    });
  }

  private async compose(
    saleReturn: SaleReturn,
    manager?: EntityManager,
  ): Promise<ExchangeSummary> {
    const run = manager ?? this.dataSource.manager;
    const [sale, supplierCredit] = await Promise.all([
      saleReturn.replacementSaleId
        ? run.getRepository(Sale).findOne({
            where: { id: saleReturn.replacementSaleId },
          })
        : null,
      run
        .getRepository(PurchaseReturn)
        .findOne({ where: { linkedSaleReturnId: saleReturn.id } }),
    ]);
    const returnCredit = Number(saleReturn.totalAmount);
    const newSaleNet = sale ? Number(sale.netAmount) : 0;
    const cashCollected = sale ? Number(sale.paidAmount) : 0;
    return {
      saleReturnId: saleReturn.id,
      returnNo: saleReturn.returnNo,
      createdAt: saleReturn.createdAt,
      customerId: saleReturn.customerId,
      invoiceNo: sale?.invoiceNo,
      saleId: sale?.id,
      returnCredit,
      newSaleNet,
      cashCollected,
      difference: Number((newSaleNet - returnCredit - cashCollected).toFixed(2)),
      supplierCreditNo: supplierCredit?.returnNo,
      supplierCredit: supplierCredit ? Number(supplierCredit.totalAmount) : 0,
      // An exchange is reversed when BOTH sides are — a half-reversed exchange
      // can only exist mid-failure, and reporting it as reversed would hide
      // the live leg.
      reversedAt:
        saleReturn.reversedAt && sale?.reversedAt ? saleReturn.reversedAt : null,
      reversalReason: saleReturn.reversalReason ?? null,
    };
  }

  private async bindNewSaleSerials(
    manager: EntityManager,
    sale: Sale,
    dto: CreateExchangeDto,
  ): Promise<void> {
    const itemRepo = manager.getRepository(Item);
    for (const ln of dto.saleLines) {
      const it = await itemRepo.findOne({ where: { id: ln.itemId } });
      if (!it) throw new NotFoundException(`Item ${ln.itemId} not found`);
      if (!it.tracksSerials) continue;
      const provided = (ln.serials ?? []).map((s) => s.trim()).filter(Boolean);
      if (it.serialRequiredOnSale && provided.length !== ln.quantity) {
        throw new BadRequestException(
          `${it.name}: ${ln.quantity} serial number${ln.quantity === 1 ? '' : 's'} required (got ${provided.length}). One serial per unit.`,
        );
      }
      if (
        !it.serialRequiredOnSale &&
        provided.length > 0 &&
        provided.length !== ln.quantity
      ) {
        throw new BadRequestException(
          `${it.name}: either supply ${ln.quantity} serial${ln.quantity === 1 ? '' : 's'} (one per unit) or leave the box empty.`,
        );
      }
      if (new Set(provided).size !== provided.length) {
        throw new BadRequestException(
          `${it.name}: duplicate serial numbers within the line.`,
        );
      }
      for (const serial of provided) {
        await this.itemSerials.bindToSale(
          {
            serial,
            itemId: ln.itemId,
            saleInvoiceNo: sale.invoiceNo,
            soldAt: sale.createdAt,
            soldToCustomerId: dto.customerId,
            warrantyDays: it.hasWarranty ? it.warrantyDays ?? undefined : undefined,
            warrantyType: it.hasWarranty ? it.warrantyType ?? undefined : undefined,
          },
          manager,
        );
      }
    }
  }
}
